### ISSUE TITLE
Doesn't compile with go 1.5

### ISSUE THREAD

**Issue by ncw** [ncw/iprime#1]
Probably due to the recent changes in the assembler and the rather complex macros :-(

```
./mod_math_amd64.s:75: expected '(', found 1
./mod_math_amd64.s:80: undefined label mod_reduce
./mod_math_amd64.s:85: expected '(', found 1
./mod_math_amd64.s:89: undefined label mod_mul
./mod_math_amd64.s:93: expected '(', found 1
./mod_math_amd64.s:117: undefined label mod_sqr
./mod_math_amd64.s:118: expected '(', found 3
./mod_math_amd64.s:119: undefined label mod_shift
./mod_math_amd64.s:120: expected '(', found 6
./mod_math_amd64.s:121: undefined label mod_shift
./mod_math_amd64.s:122: expected '(', found 9
asm: too many errors
```

**Comment by cznic** [comment]
FYI: Wanted to bypass this issue by downloading the binary as documented in the README

> Download the relevant binary from
> - http://www.craig-wood.com/nick/pub/iprime/

but the above URL returns a 404 error.

**Comment by ncw** [comment]
@cznic - thanks for the heads up.  Will attempt to fix compiling, or find the binaries shortly!

**Comment by ncw** [comment]
I've tracked this down to a regression in go - see bug report golang/go#13499

**Comment by cznic** [comment]
:+1:
